### ISSUE TITLE
Add permission system

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#14]
One of the most critical things we still have to implement is the permission system.
@daranable already made a permission system here: https://github.com/daranable/Starfall/tree/permissions

As far as I can tell, this just needs to be ported to GM13 and could be considered done.
(And we need providers with some default values)

I'm probably going to start on this tomorrow if no one objects.

**Comment by Xandaros** [comment]
Okay, seriously. I hate vgui.
I can't get it to look somewhat decent, let alone how I want it to look.

I'm going to finish the permissions system but leave out anything that has to do with vgui, effectively leaving the default provider unconfigurable.
Someone else has to do that part, I just can't do it.

**Comment by Xandaros** [comment]
What should happen if an action is not allowed? Should the chip crash? Ignore the action? Go haywire?

**Comment by daranable** [comment]
What we really need is exceptions, but that is a whole different ball game.  With exceptions if they go uncaught they throw an error, otherwise the chip can handle it gracefully.

If it throws an error, we need to make sure to expose a function to check if you can do a certain thing, so that way trying to use something that they may or may not be able to will be a headache.
