### ISSUE TITLE
render.readPixel

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#188]
http://wiki.garrysmod.com/page/render/ReadPixel

Not quite sure what it does, but if it does what I think it does, I think it does deserve to be part of the render library.

Does.

**Comment by wraith321** [comment]
I think it does exactly what you think it does and if that is the case, it would offer a nice way for making Starfall cams which could capture screenshots :).

**Comment by awilliamson** [comment]
Some testing will need to be done :) Throwing a few quick tests together now.

EDIT: Initial starfall hackery done. Why this function returns 3 numbers I've no idea. We'll probably make ours spit out a color because that's expected behaviour.

EDIT2: Can't get it to return anything other than 0 0 0 :/ Odd.

EDIT3: Even after iterating over all pixels, they're all 0,0,0. Which is impossible after I've specifically set the color. Either I'm doing it wrong or readPixel is broken. Found old post from 2011 from Garry saying he'd fixed readPixel from returning 0,0,0 instead of nil.

**Comment by Xandaros** [comment]
@wraith321 I think what you mean is this: http://wiki.garrysmod.com/page/render/RenderView
I was thinking about adding something like that - all in good time.

I thought readPixel can rad back what you drew on a screen, which could be very useful.
I'll do some tests in the evening, when I'm back from Uni, unless you figure something out, @awilliamson

**Comment by wraith321** [comment]
Reading the pixels actually requires dumping the render target everytime and I guess that could be a big performance problem.
You would either need to expose render.CapturePixels() too and let the user handle it efficiently or refresh it automatically every tick when pixels are read.

Here is an usage example:
http://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index18da.html

edit: @awilliamson The fix was only for pixels that are out of bounds, your problem was not using render.CapturePixels() before I guess.

**Comment by awilliamson** [comment]
@wraith321 I used the official wiki which mentions nothing about dumping. This is why I still disagree with the wiki wipe. So much information loss. Will need to discuss if it's worth implementing with @xandaros and if so, how to go about it.

**Comment by Xandaros** [comment]
Since we are using CPU-time now, is there any issue left about implementing it?
We can just expose CapturePixels and if people abuse it, they will simply quota.

**Comment by awilliamson** [comment]
Just hacked in both CapturePixels and ReadPixel into a single player game.

``` lua
SF.DefaultEnvironment.capturePixels = render.CapturePixels
SF.DefaultEnvironment.readPixel = render.ReadPixel
```

I then played around with it in singleplayer, used the 'minecraft shader' example and made a neat little demo which will probably make it into an example at some point if @Xandaros agrees ofc.

``` lua
--@name Capture Pixels Test v2
--@author INP - Radon

-- If this quotas, might do during initialisation, then just lower the coefficients.
local function checkQ ()
    return ( quotaUsed() < quotaMax() * 0.5 ) and ( quotaAverage() < quotaMax() * 0.5 )
end

-- Initialisation
local co = coroutine.create( function ()
    render.clear()
    -- Step is 2 because it's much quicker to initially render. 256*256 effective rather than 512*512
    for i = 0, 512, 2 do
        if not checkQ() then coroutine.yield() end
        for j = 0, 512, 2 do
            if not checkQ() then coroutine.yield() end
            render.setColor( Color( 255/512 * i, 255/512 * ( i + j / 2 ), 255/512 * j ) )
            render.drawRect( i, j, 1, 1 )
        end
    end
end )

-- Lots of fiddly coroutine making swapping resuming etc.
-- Unless you want to render 512*512 in a single frame.
hook.add( "render", "", function ()
    if coroutine.status( co ) == "dead" then
        co = nil
        local exp = 1
        co = coroutine.create( function ()
            while exp < 9 do

                -- On the first pass this exp is 1, therefore step is 2, which maps perfectly to our generation.
                -- This is why the first pass after initialisation removes the gaps, as it never reads the black.
                local spacing = 2^exp

                -- Same as render.CapturePixels from GLua, this was just set as SF.DefaultEnvironment.capturePixels = render.CapturePixels
                capturePixels()
                for x = 0, 512, spacing do
                    if not checkQ( 0.8 ) then coroutine.yield() end
                    for y = 0, 512, spacing do
                        if not checkQ( 0.8 ) then coroutine.yield() end
                        -- Same as render.ReadPixels from GLua, same process as above.
                        local r, g, b = readPixel( x, y )

                        render.setColor( Color( r, g, b, 255 ) )
                        -- Instead of the rects representing 1 pixel w & h it's now equal to the gap between them.
                        render.drawRect( x, y, spacing, spacing )

                    end
                end

                exp = exp + 1
                coroutine.wait( 3 )
            end
            hook.remove( "render", "" )
        end )
    elseif coroutine.status( co ) ~= "running" then
        coroutine.resume( co )
    end
end )

```

Some screenshots:
![](http://cloud-4.steampowered.com/ugc/546381409375767041/B1F444108F8DB83499ACD8D46A32806554638A0F/1024x576.resizedimage)
![](http://cloud-4.steampowered.com/ugc/546381409375768492/31F4412E9058EEA28D04345C1739C9ED29F0A5B0/1024x576.resizedimage)
![](http://cloud-4.steampowered.com/ugc/546381409375770013/3615B1106506BDB5FBBA1FDF465A1EA7B2F7BDF7/1024x576.resizedimage)
![](http://cloud-4.steampowered.com/ugc/546381409375772029/09A2A55B4F9C49B5E42AD8FA49197A0A8D0D1C5A/1024x576.resizedimage)

As part of my tests I innocently added some drawText to display current step exponent, didn't end well, as capture pixels grabbed that. As far as I can see the capture Pixels doesn't appear to affect performance that much. From this initial test it works so well that it actually had to add a coroutine.wait, but that's most likely due to the reduced number of iterations in the nested fors.

**Will add these two functions as a pass through into the render library and most likely make readPixel return a color object and all pixels would have 255 alpha for obvious reasons.**

**Comment by Xandaros** [comment]
Actually,if you create a render target, it can be transparent. The main render target always has a opacity of 255, but the the other ones don't...
But it's not like we can detect that. :(
