### ISSUE TITLE
sound:setVolume doesn't take the delta argument, always errors

### ISSUE THREAD

**Issue by TylerB260** [INPStarfall/Starfall#221]
The code for the sound:setVolume function doesn't include a delta variable, so it always errors.

addons/starfall-develop/lua/starfall/libs_sh/sound.lua:119: bad argument #2 to 'ChangeVolume' (number expected, got no value)

**Comment by Xandaros** [comment]
Supersedes #174 (Because that was closed for some reason)

**Comment by awilliamson** [comment]
Working on a complete rework of the sound library. There's a lot of global functions in GLua that are rough clones of entity ones, many do the same thing. All take different arguments, all of which aren't documented unless you search through valve's developer pages to find the ENUM types. So it's taking some time because of all that.
