### ISSUE TITLE
Broken string.explode

### ISSUE THREAD

**Issue by RoboLV** [INPStarfall/Starfall#228]
When i trying to explode string i got :
local tab = string.explode( "#", "This#is#String" )
for k,v in pairs( tab ) do
   print( k )
end

i got this
1

only one element in table

**Comment by awilliamson** [comment]
Have you tried seeing what the value is at that index. I hazard a guess that it's the original string.

**Comment by Xandaros** [comment]
This is indeed a bug, but not in the way you expect.
If starfall has a string.explode function, that is not intentional, because standard Lua doesn't have that…

**Comment by awilliamson** [comment]
As @xandaros said I don't believe we have it. please ensure you test it in single player or on our server at inp.io. To ensure the problem is related to our original code.

**Comment by shadowscion** [comment]
[I don't know if this is what you are talking about or not](https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/libs_sh/builtins.lua#L154)

**Comment by Xandaros** [comment]
Yup, that's a bug - we need to get rid of that.
That aside, as you see we are passing your arguments straight to garry's function, complain to him :P

**Comment by awilliamson** [comment]
Finally got around to looking into this. The param order is different in our version of string.explode. It follows string.explode( str, sep, pattern ) whereas Garry's does string.Explode( sep, str, pattern ). Just tested both functions from within game using GCompute. Our explode function works if you pass it the correct order. Reason it would return empty is because you're trying to separate a '#' with  "This#is#String".

Unsure what we want to do with this. string.Explode is implemented in pure Lua from Garry using gsub. So either learn to use what Lua provides or you can add Garry's function into your libraries. So I'd hazard a guess that it will be getting removed, I'll just get @Xandaros to confirm this then we'll get rid of it.

https://github.com/garrynewman/garrysmod/blob/bdad5afc2860959c224c2c01c8906aca240750dd/garrysmod/lua/includes/extensions/string.lua#L34

For anybody interested in seeing how it works.
