### ISSUE TITLE
Math.sin not working as expected

### ISSUE THREAD

**Issue by sirdabalot** [INPStarfall/Starfall#229]
Hey, as the title says math.sin is not producing expected results, I have made a simple test program to draw sections on to a screen; this is the code:

``` lua
--@name test
--@author Sirdabalot
--@sharedscreen

if SERVER then

else
    function renderStuff( )
        render.clear( Color( 0, 0, 0, 255 ) )
        render.setColor( Color( 255, 255, 255, 255 ) )
        for a = 0, 360, 45 do
            local range = 256
            local x2 = math.sin( a ) * range
            local y2 = math.cos( a ) * range
            render.drawLine( 256, 256, 256 + x2, 256 + y2 )
        end
    end

    hook.add( "render", "renderHook", renderStuff )

end
```

Instead of sectioning the screen in 45 degree angles I'm presented with this:
![image](https://cloud.githubusercontent.com/assets/5678352/3638806/ffedb6ea-1061-11e4-862f-bf1a0c533e2b.png)

Which just isn't right; can anyone help me?

**Comment by awilliamson** [comment]
Because trig functions take radians, not degrees. You'll mainly work in radians where accuracy is key, as you can represent them as fractions of Pi, I used them extensively throughout A-Level Maths.

``` lua
--@name test
--@author Sirdabalot
--@sharedscreen

if SERVER then

else
    function renderStuff( )
        render.clear( Color( 0, 0, 0, 255 ) )
        render.setColor( Color( 255, 255, 255, 255 ) )
        for a = 0, 360, 45 do
            local range = 256
            a = ( a / 360 ) * 2 * math.pi
            local x2 = math.sin( a ) * range
            local y2 = math.cos( a ) * range
            render.drawLine( 256, 256, 256 + x2, 256 + y2 )
        end
    end

    hook.add( "render", "renderHook", renderStuff )

end
```

A circle consists of 2Pi Radians. It's the angle subtended by an arc whose length is equal to the radius of the circle. As such a radian is fixed regardless of the radius size, the angle is very much the same for all circles. If you know there are 360 Degrees in a circle as well as 2PI Radians, then you can quickly figure out how to convert between them.

``` lua
local rads = ( deg / 360 ) * 2 * math.pi
local deg = ( rads / ( 2 * math.pi ) ) * 360
```

A good resource for an introduction to radians would either be an A-Level Maths class or online resources such as Khan academy or a number of youtube videos.

Here is the Khan Academy link for you, I find they are usually very good with their videos.
https://www.khanacademy.org/math/trigonometry/unit-circle-trig-func/radians_tutorial/v/introduction-to-radians

What you've shown is actually a polar coordinate system, and used trigonometry to find the x and y offsets by creating triangles. Below is an example working purely in Radians, the code looks more complicated but functions the same and is arguably preferred.

``` lua
--@name test
--@author Sirdabalot
--@sharedscreen

if SERVER then

else
    function renderStuff( )
        render.clear( Color( 0, 0, 0, 255 ) )
        render.setColor( Color( 255, 255, 255, 255 ) )
        for r = 0, 2 * math.pi, ( 1 / 5 ) * 2 * math.pi do
            local range = 256
            render.drawLine( 256, 256, 256 + math.sin( r ) * range, 256 + math.cos( r ) * range )
        end
    end

    hook.add( "render", "renderHook", renderStuff )

end
```

![image](http://puu.sh/ak9xW/60df871f2d.jpg)

**Comment by sirdabalot** [comment]
Ah, my mistake, I guess other languages converted to radians for me. xD I'll close the issue, now. Thanks for your help. =D
