### ISSUE TITLE
Add trace.QuickTrace

### ISSUE THREAD

**Issue by AlexALX** [INPStarfall/Starfall#261]
Can you please add this function http://wiki.garrysmod.com/page/util/QuickTrace to starfall trace liblary? This allow trace from startpos + direction and get endpos (without know end pos). This needed for example when try trace using getpos+angles of prop etc, because right now i can't get it work correct with angles (i need trace with direction + 200 game units). 

I also can help with code for this, and create pull request if needed.

This will be very good, thank you in advance and sorry for my english.

**Comment by awilliamson** [comment]
I don't understand why you need QuickTrace. It's just a convenience function added by Garry, that's why it's not in our trace lib, and it's pretty straight forward from the looks of it.

https://github.com/garrynewman/garrysmod/blob/4eb9bb19dcfac06007691376ecaf2dbc56efa6b2/garrysmod/lua/includes/extensions/util.lua#L55

If you want that functionality in your code use our trace function. End pos is just the origin, plus a direction multiplied by your length.

**Comment by AlexALX** [comment]
Ow sorry then, didn't know about this. Thank you.
