### ISSUE TITLE
Change --@sharedscreen to --@shared and make it work for screen and processor.

### ISSUE THREAD

**Issue by thegrb93** [INPStarfall/Starfall#295]
I can do this, but first I need to know if it's a good idea and will be approved.

**Comment by Xandaros** [comment]
Well, we originally wanted to completely separate starfall instances from their entities, so there wouldn't be a concept of "screen" or "processor" on that level.
We'd then have --@server and --@client, which would determine where the code is run. (Can also supply both)

The question that remains, however, is: What if the user doesn't specify anything? Do we have some default behaviour? will it error?

Renaming sharedscreen to shared is not really a good idea at the moment, since we'd only end up renaming it again, causing us to break old code twice instead of once.

**Comment by thegrb93** [comment]
I think it should always be shared with the option of using --@server or --@client to specify that the code is server-side only or client-side only. I think the only difference between the processor, screen, and hud (to be made) should be the way the render hook gets called.

**Comment by thegrb93** [comment]
Actually what if we make it so the user can declare what the following code runs on. --@server, --@client, and --@shared with shared as default.

```
print("Shared print")

--@server
entities.self():setColor(Color(0,0,0,255))

--@client
hook.add("render","blah",function() end)

--@shared
print("another shared print")

--@client
print("client print")
```

Then we can split the script into which parts run on the server and which parts run on the client.

**Comment by awilliamson** [comment]
--@server and --@client would be preprocessor statements. Putting it inline would not work. We have a method for switching, surprisingly built into GLua, called SERVER and CLIENT.

``` lua
if SERVER then
    print( "Serverside stuff" )
end

-- You can use else instead of 'end', and another 'if CLIENT' section.

if CLIENT then
    print( "Some CLIENT stuff" )
end
```

The point that @Xandaros is trying to make, is with explicit preprocessor statements what is the expected behaviour for a script which is either not explicitly stated, or has both. I have discussed this with him briefly. As I mentioned to Xan when I brought these issues to his attention, we have been wanting this freedom to execute Lua on either 'platform' for a while now. As Xan mentions, we've been looking at separating the physical representation from the instance which the code runs, this would then allow us to interpret the code on whichever 'platform' we want without affecting our interface to the users.

**Comment by thegrb93** [comment]
I'm aware they are preprocessor statements. They could be used to split the server and client code apart so that the server code doesn't get sent to the client. If you guys don't care about that then yeah SERVER and CLIENT work fine, but the starfall processor doesn't allow shared code for whatever reason.

The expected behavior for a script that doesn't have them explicitly stated should be shared.

**Comment by Xandaros** [comment]
> The expected behavior for a script that doesn't have them explicitly stated should be shared.

Why?

**Comment by thegrb93** [comment]
Because you haven't stated whether it is server-side or client-side. Plus shared is probably more common.

**Comment by thegrb93** [comment]
I just made the processor always shared, and the screen and hud entity can be linked to the processor using the component tool.
