### ISSUE TITLE
Color metamethods, not able to compare colors

### ISSUE THREAD

**Issue by funkake** [INPStarfall/Starfall#34]
A:getColor()==Color(0,0,0)    even if A:getColor() returns 0,0,0 I am not able to compare them and get a sensible result

tested this and it worked!
    if     A:getColor()["r"]~=Color(0,0,0,0)["r"]
    and A:getColor()["g"]~=Color(0,0,0,0)["g"]
    and A:getColor()["b"]~=Color(0,0,0,0)["b"]

therefore i suspect that the color type is missing some logic metamethods

**Comment by awilliamson** [comment]
Interesting that you use 'and' instead of 'or'. The implementation for Color's, as provided by Garry, are strictly tables only. I simply let colors be recognized as a type within Starfall code so that other functions could type check for it, without doing ridiculous clr.r and clr.g etc checks.

https://github.com/garrynewman/garrysmod/blob/ff51a59d5a821dec3c8f524631c86150b3e4744d/garrysmod/lua/includes/util.lua

You can see in the above that Garry is just returning a table with r, g, b, a fields. Gmod's implementation of Colors doesn't contain any comparison operators or multiplicative operators. I will talk with the other developers about adding this into Starfall. The alternative would be to propose these changes as a PR into that GMod repo itself.

**Comment by awilliamson** [comment]
I think for now @Xandaros and I decided that if comparison metamethods are required, then people can write them themselves.

If this isn't the case then feel free to reopen and reiterate.
