### ISSUE TITLE
Merging with GmodStarfall/Starfall

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [INPStarfall/Starfall#38]
What are your plans, if any, for merging back into GmodStarfall/Starfall?

I am glad that people are developing SF since I've stepped away from Garry's Mod, but I would still like to review and discuss changes to it, which I would greatly prefer be done on the official repository. That's why I'm a bit upset that this fork just started doing its own thing while only submitting one ill-formed pull request to the official repo.

I would like to merge this fork with the official repo, but I don't want to do so blindly. Yet since this fork is so divergent, reviewing each change would take up a lot of time.

Additionally, I have a few design suggestions that would make SF easier to use and thinner, but I do not wish to work on anything Garry's Mod related anymore.

**Comment by Xandaros** [comment]
I am really surprised to see you open an issue :D

Let me try and explain our reasoning behind the split:
When I joined Starfall on the awilliamson repo (which was the only working version of starfall), Radon said that the changes will eventually be merged into the main repo, but we (Radon, Divran and I) didn't know about any guidelines, as these were not (and still are not) clearly set or viewable.

Daranable then came to us and urged us to get our changes into the main repo, to prevent the branches from diverging any more, but he also told us about the guidelines and their reasons.

Now, Divran's commits were a mess and most needed to be split or renamed. I literally spent hours fixing his commits (That is also one of the reasons he has no access to the new repo)

I sent Daranable a list of the Pull Requests I wanted to make. Rather than sorting commits by features, we agreed on sorting them by the part they modify (mostly libraries) and get the PRs changed if need be. Daranable also said that he would be a bit more lax about accepting the PRs, since he knew how much work it was to get Divran's commits even remotely organised. (To be fair, some of Radon's commits were not perfect, either and I can think of at least one flawed commit I made, I do not want to sound like I am picking on Divran personally)

After I made the first Pull Request, which was absolutely necessary for all the other PRs to work, you jumped in and said "nobody merge this", which left daranable choice-less. (You are the repo's owner, after all)

Furthermore, you did not provide very detailed instructions about what needs to be changed and after I got into the mood of doing "git magic" again about one month later, you only said that it was a whole month ago and cannot remember.

Since you did not tell us what to change, what were we supposed to do? Guess?

That was our initial reason. When we decided to give up on merging our changes into the main repo, we set up our own guidelines (I know you do not like the style guidelines and truth be told, I do not like each and every guideline, either. These guidelines were a compromise between the three of us and as you are probably well aware, style guidelines are a controversial subject and it is impossible to please everyone) and release cycle. We even set a date for initial release.
We actually made quite an effort towards project management.

We noticed that we also have a different philosophy about Starfall. The Starfall in the main repo seems to be modeled after E2, while we decided to model functions more closely to (G)Lua.
This one is actually the biggest reason we are reluctant to merging back into the main repo now, because we believe that E2 is terribly designed and Starfall should behave more closely to the (G)Lua backing.

Finally, and I am sorry if this sounds condescending, why do you care so much if you do not want to do any Garry's Mod related development? If we were to merge this fork with the main repo and have you review all following changes, we would not be able to develop in the fashion we want without getting any benefit from it. (Apart from it being in the main repo, but since no one is developing on there, this really only means that you own it.)

I hope I was able to clarify our reasons behind this split without sounding like an utter jerk. I have to stress that we really appreciate your vast amount of work on Starfall and that we do not do this to tick you off or steal the project from you.

Please feel free to open issues with any suggestions you have.

**Comment by ColonelThirtyTwo** [comment]
I'm sorry if I wasn't too clear on what to do with the pull request. I'd greatly prefer one feature per pull request (though for the library files, files and features seem to go hand in hand), but I can understand grouping a bunch of small bugfixes into one request. My bone to pick with that request was that in addition to bugfixes, it also included two new features: `GetType` replacing `type` and the editor animation, both of which were things that belong in their own pull requests and that I would like to have discussed more. Additionally, Divran was fixing the bugs I pointed out on a different branch, and thus were not being added to the pull request.

I was also aiming for modeling SF close to GLua (even if I did retain some of E2's junk out of force of habit, like the 'context' thing). But as I worked towards that goal, I started noticing the inconsistencies and issues with the Garry's Mod API (GLua seems to be stuck in a C++ style, with stuff like Ex functions where dynamic language features like optional arguments would be better. It also breaks `require` and replaces `loadstring` with `CompileString` for no good reason, but now I'm starting to rant). So I kinda became stuck in a pickle; do I stick with GLua conventions or do I try to improve upon them?

Even though I'm not working on it, I'd still like to see it succeed; I guess its sorta a 'parental attachment' I have with my code. :P.

**Comment by awilliamson** [comment]
I perfectly understand the 'parental attachment' to the Starfall project. We're all eager to see Starfall succeed and be the most it can be. Everybody that is currently working on it really believes in its potential. I saw this potential years ago when I first came across it. It's partially why Divran and I came to you asking for your blessing on reviving Starfall.

As Xandaros said, the ethos of Starfall, as we've mentioned previously, is more of a purist approach. From the code before we began work it seemed as though Starfall was leaning towards E2 naming to make it an easier crossover.

We will always welcome your input and suggestions for streamlining or optimizing. We are all grateful for your initial work on Starfall even if you don't wish to code for GMod anymore.

I know it may seem at times like we're doing things differently and that you feel out of the loop, but being the father of Starfall you will always be known and credited for the great idea. Starfall is gaining popularity every day, the more we add, the more we amaze people with the possibilities that SF gives them. We're all proud of our work, and I hope that we will be able to take any suggestions you have and implement them without you needing to waste your time developing yourself. 

It would mean a lot to all of us if we had your blessing to go ahead with development of Starfall with the purist approach and also to have the possibility of consulting with you on future developments.
