### ISSUE TITLE
Cannot upload SF code

### ISSUE THREAD

**Issue by shadowscion** [INPStarfall/Starfall#45]
This error has resurfaced and can't be be fixed without a server restart. Not exactly sure how to reproduce it this time, as it wasn't me who caused it.

**Comment by Xandaros** [comment]
This happens if you spawn a screen and undo it immediately, I think. Did they get an error message saying something about "CodeSent"?

If it did, I will fix this as soon as I have the time, Uni is killing me right now, sorry.

But this is hardly enough information to do any debugging, at least an error message is required. If this is a different matter, we will not be able to debug it without experiencing it ourselves by using starfall…

**Comment by awilliamson** [comment]
Is this still happening? I know a server owner mentioned the dreaded "CodeSent" bug the other day to me when spawning a screen for the first time, didn't have any problems after that error in spawning new screens to my knowledge.

**Comment by Xandaros** [comment]
At least "CodeSent" is still happening. I might be able to fix it soon™
