### ISSUE TITLE
Add convar to limit traces

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#58]
Currently you can do as many traces as the op count allows.
I compared a SF chip that only has an empty while loop and one that does traces one after the other.

The first one did not lag at all, the second one lagged quite a bit and used more cpu time.
But even if I limit the time the second while runs, it lags the game a lot.

**Comment by awilliamson** [comment]
This shouldn't be an issue once our proper method of running scripts is implemented. Could be a temporary fix if we're releasing this under the pretense of general user use, rather than the admin/trust only one we have now. 

It would at least allow it to not be exploited into crashing a server until such a time that we have our planned system implemented.

**Comment by awilliamson** [comment]
Discussed with @Xandaros, at the current time this is not wanted as an enhancement, could be reopened at a later date if our decision changes.
