### ISSUE TITLE
Change ents.setNotSolid to ents.setSolid

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#60]
Although most of the time you start with a solid entity and want to change that, setSolid makes more sense than setNotSolid in my opinion.

**Comment by ColonelThirtyTwo** [comment]
Wait, is there both `setSolid` and `setNotSolid`? Wtf garry, why?

**Comment by Xandaros** [comment]
Yes, although they are different.
I just disagree with a function name "setNotSolid". Why would anyone name it like that?

**Comment by awilliamson** [comment]
If the GLua function for an entity is named that way, then we'll pass it through. As I've previously mentioned with @Xandaros certain functions we may not personally like, but we're just providing a layer and I'd like to try stick as close to 1:1 as possible so that people may use existing documentation for GLua to code with starfall as effortlessly as possible.

Possibly add a notion in the document generating comments to bring to light their nuances and guide people in their correct usage.

**Comment by Xandaros** [comment]
I disagree with sticking so close to GLua.
GLua has some very bad standards. (If any)

IMO this is a perfect example. Why have a function "setNotSolid" which sets a value that defaults to false isntead of "setSolid", setting a variable that defaults to true.
Makes for a better name in my opinion.

On that note, garry's "setSolid" should be called "setSolidType", "setSolidityType", or something similar, as it changes the solidity type of the entity.
(Or maybe even collisionType, since it basically changes whether to use bounding box or collision model and other options.
Can you guess that from "setSolid"? His naming is not very intuitive, although this might actually be valves fault...)
http://wiki.garrysmod.com/page/Entity/SetSolid

Sure, people that are used to GLua might appreciate it if we stick close to GLua, but I'm sure even they don't like it.

**Comment by ColonelThirtyTwo** [comment]
I agree with renaming to "setSolid" ~~but not with "setSolidType". It's a boolean attribute, no need for an enum with two elements.~~

~~Setting an entity as intangible just makes it so that the engine doesn't preform collision detection with that object; it doesn't change "whether to use bounding box or collision model"~~

Didn't realize SetSolid now takes an enum. I agree with Xandaros now.

**Comment by awilliamson** [comment]
Oh, I know that the naming is just horrible. I've agreed with all the reasons stated for the rename, but if we start changing little things here and there then it's not long until we have like E2 has them. Where methods are named whatever which way they want to be regardless of their origins.

Perhaps this is an extreme case which does require intervention, but I don't want to be making a habit out of this. I'd like to try to stick as close as possible to existing GLua ( obviously with correction to camelCasing ) when we talk about things specifically in GLua, such as ents, not the additions to the maths library that Garry added.

If we point out the change in our documentation pointing to the correct GLua function then I'd probably be happy. I just don't want a repeat of what E2 did, where people are so used to their weird way of method naming that when they see the 'actual' functions they don't recognise them.

**Comment by Xandaros** [comment]
As I said before, as long as we stick to a naming convention, it won't become E2. (Like getters starting with "get")
And most GLua functions follow this. However, some are just very unintuitive or unnecessary. (C-style *Ex function, for example. They are necessary in C, but can be replaced with language features in Lua. [And C++, for that matter...])

**Comment by awilliamson** [comment]
Agreed to change the naming from what source sets so that it makes more sense. Will want a note in the documentation so that users may look up the differences in GMod docs.
