### ISSUE TITLE
Signal library

### ISSUE THREAD

**Issue by Xandaros** [INPStarfall/Starfall#75]
We need a signal library to replace net library and for sending data between processors/screens.

See #1

**Comment by Xandaros** [comment]
@ColonelThirtyTwo suggested through indirect messages (long story) to name the signal library "event" rather than "signal", which I think might be a good idea. Thought?

**Comment by awilliamson** [comment]
Was speaking with @Xandaros at the time and thoughts that 'event' sounds like a suitable name. However it won't just be events it will also be messages.

**Comment by Divran** [comment]
Why don't you make the hook library able to send to other instances? All you'd need to do is change hook.run from instance:runScriptHook to loop through the instances like this function https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/libs_sh/hook.lua#L86 does

**Comment by Xandaros** [comment]
Hmm, remote hook execution might be an idea, as well...

**Comment by Divran** [comment]
Also, it appears you already have a global tables library. This library can be used by anyone to make their own instance->instance library, since you can simply save some functions on a global table. Really the only advantage of having a global table library in SF is if you add E2's gTableSafe function (which returns an unhackable global table for use in E2 games).

**Comment by Xandaros** [comment]
The problem with global tables is, they are global. You can't send a message to an instance owned by another player, without anyone else being able to read it, too. And the receiver is not able to verify the origin of the message.
Of course, you could encrypt and sign the messages, but in my opinion that is way too much processing power for general use.

Another thing with global tables is, that the receiver has to poll for changes. A signal/event library would fire a hook on the receiver. (Or a remote hook execution, doh...)

Remote hook execution might be a better way, actually, since a library would end up calling a hook anyway.
However, I think you should only be able to call a single hook, like "signal" , "event" or "remote" or something. And the arguments would be (origin, ...) with the varargs being whatever the sender called.
We also need to figure out how to select whether you want to send to the client instance or the server instance of something.
Alternatively change the net library to only be able to send from client instance to server instance of the same screen or vice-versa... You'd have to make all screens shared that want to receive from server, though :/ Makes for some instances that do almost nothing, not sure if I like it that much.

**Comment by Divran** [comment]
> You can't send a message to an instance owned by another player, without anyone else being able to read it, too. And the receiver is not able to verify the origin of the message.

That's what you can use E2's gTableSafe for.

> Another thing with global tables is, that the receiver has to poll for changes.

The receiver doesn't have to poll for changes if you save a function to the gtable which you then call whenever.

**Comment by daranable** [comment]
@Xandaros Should we want a starting point here is an implementation I had started on a while back: https://github.com/daranable/Data-Signals
I designed it to also solve another problem not mentioned here, this implementation could replace E2's and allow for any processor type to send data to any processor type.

@Divran the problem with a system like that, is then you start running into issues when you want to send a piece of data to X unknown entities, they have to all register their own callbacks etc.

**Comment by Divran** [comment]
I tested my theories on the globaltables library and while it is possible to call functions on other instances, I believe the ops gets added to the calling chip rather than the receiving chip, which kind of defeats the purpose. So while it is a fun derp hack, it's not very useful.

@daranable isn't that library pretty much exactly like E2's though? SF is Lua, so we don't have to mimic E2 at all.

Xandaros had the good idea that we could have a specific hook be shared, so using hook.run on that would broadcast it on all instances.

**Comment by awilliamson** [comment]
@Divran I thought we'd agreed that globaltables ( for this event stuff ) is a horrible idea and that you would then need a hack of a hack in order to get them functioning? Rather than beating around the problem, we should try solving it down a more proper route.

@Xandaros If the remote hooks are a more fleshed out version of what we were discussing yesterday with events then It sounds good. Having chips able to register for something another will fire is good. More would have to be designed and fleshed out at the moment, but the initial idea seems nice.

**Comment by daranable** [comment]
So, the problem I foresee with using a hook system to do remote signaling is how is someone wanting to receive data or not receive data going to do access control to that?  With an implementation of Signals like the above by default you get nothing and have to register for more.

Also, please correct me if I am wrong, the last time I looked at expression 2, expression 2 functions are not first class, and thus haven't been able to be registered for callbacks, and thus the remote hook execution would mean that starfall can not send data back and forth with e2.  I personally would love to see whatever signaling system we set up be completely not tied to starfall alone, and allow it to work for anything that registers with the library, in the case of what I have not even tied to processing entities.

@Divran Yes it it is a little reflective of what E2's is, but that is because a PubSub system like it actually makes sense for this purpose.  in the implementation, yes I modeled it after e2 a little because I wanted to make allowances for it to replace e2's Data Signals in place without breaking their code.

**Comment by Divran** [comment]
> @Divran I thought we'd agreed that globaltables ( for this event stuff ) is a horrible idea and that you would then need a hack of a hack in order to get them functioning? Rather than beating around the problem, we should try solving it down a more proper route.

That's basically exactly what I said?

**Comment by ColonelThirtyTwo** [comment]
First, please please please do not call them signals. It's a very E2 name for them. Please call them events.

You can send closures over global tables and call them on other instances, to avoid polling. Not that I endorse globals. @Divran the ops should go on the chip calling the function, because that's the one that is running.

**Comment by Divran** [comment]
> @Divran the ops should go on the chip calling the function, because that's the one that is running.

But then you can't make peer-to-peer chips? I mean then you can't have one chip tell another which task to work on, because it'd in fact be the first chip doing all the work anyway.

**Comment by daranable** [comment]
@Divran using that system the chip that is going to work on something could simply register a callback for the next tick, and do the processing then, no I don't think that is ideal but it is a way it /can/ be done.

But I believe we all agree at this point using Global Tables is just out.

**Comment by Divran** [comment]
> @Divran using that system the chip that is going to work on something could simply register a callback for the next tick, and do the processing then, no I don't think that is ideal but it is a way it /can/ be done.

That'd require polling though, wouldn't it (which we want to avoid)? Checking to see if a callback was registered or not.

**Comment by daranable** [comment]
I don't believe it would as if the function the calling chip is calling is a closure, the function that gets called after say a timer will run in the context of the called chip.  I don't see how that would require polling.

But also talking about this facet of global tables isn't likely necessary if we aren't going to use it. XD

**Comment by awilliamson** [comment]
I think too many people are just talking about many different things that aren't related back to the core issue at hand. Can I ask that we forget about this for now whilst we get more of an idea around what the problem is and what potential solutions to it would involve. We only made the issue as a passing remark that we want something rough, we never fully outlined it.

**Comment by Xandaros** [comment]
This is how I think it should be done:
Net library gets changed so it can only send between instances of the same screen.
To send something to another instance, you call a function with varargs. This will execute a hook on the receiver with the first argument being the sender and varargs what the sender supplied.

It is a very simple way of doing it and is easily expandable on user level.
If you want to expose functions that run on the instance of the caller, just put them in a global table or send it to them with a "signal"...

(Whether we call it signal, event or something else, doesn't really matter for now. I currently think this should just be an extension of the hook library.)

**Comment by daranable** [comment]
I personally don't like the idea of having it extend the hook library.  The way Hooks in a language are used are not meant to do access control and things like that, and an event system like this in the context of GMOD really needs to have fine grained access control.  Also If people are going to learn to program in this I do /not/ want to teach them bad things about things that are used all over the place like hooks.

**Comment by awilliamson** [comment]
Ok, seriously people. Stop talking now, more will be discussed later...

**Comment by Xandaros** [comment]
Closing an issue means it's finished. It is not.
